export const POWER = "POWER("
export let calculatorButtons = [
    {
        name: "deg",
        symbol: "DEG",
        formula: false,
        type: "key",
      },
      {
        name: "rad",
        symbol: "RAD",
        formula: false,
        type: "key",
      },
    {
      name: "square-root",
      symbol: "√x",
      formula: "Math.sqrt(",
      type: "math_function",
    },
    {
      name: "cube-root",
      symbol: "∛x",
      formula: "Math.cbrt(",
      type: "math_function",
    },
    {
      name: "square",
      symbol: "x²",
      formula: POWER,
      type: "math_function",
    },
  
    {
      name: "cube",
      symbol: "x​³",
      formula: POWER,
      type: "math_function",
    },
    {
      name: "invert_sign",
      symbol: "+/-",
      formula: "negate(",
      type: "math_function",
    },
    {
      name: "open-parenthesis",
      symbol: "(",
      formula: "(",
      type: "number",
    },
    {
      name: "close-parenthesis",
      symbol: ")",
      formula: ")",
      type: "number",
    },
    {
      name: "clear",
      symbol: "C",
      formula: false,
      type: "key",
    },
    {
      name: "delete",
      symbol: "⌫",
      formula: false,
      type: "key",
    },
    {
      name: "pi",
      symbol: "π",
      formula: "Math.PI",
      type: "number",
    },
    {
      name: "cos",
      symbol: "cos",
      formula: "trigo(Math.cos,",
      type: "trigo_function",
    },
    {
      name: "sin",
      symbol: "sin",
      formula: "trigo(Math.sin,",
      type: "trigo_function",
    },
    {
      name: "tan",
      symbol: "tan",
      formula: "trigo(Math.tan,",
      type: "trigo_function",
    },
    {
      name: "7",
      symbol: 7,
      formula: 7,
      type: "number",
    },
    {
      name: "8",
      symbol: 8,
      formula: 8,
      type: "number",
    },
    {
      name: "9",
      symbol: 9,
      formula: 9,
      type: "number",
    },
    {
      name: "division",
      symbol: "÷",
      formula: "/",
      type: "operator",
    },
    {
      name: "e",
      symbol: "e",
      formula: "Math.E",
      type: "number",
    },
    {
      name: "acos",
      symbol: "acos",
      formula: "inv_trigo(Math.acos,",
      type: "trigo_function",
    },
    {
      name: "asin",
      symbol: "asin",
      formula: "inv_trigo(Math.asin,",
      type: "trigo_function",
    },
    {
      name: "atan",
      symbol: "atan",
      formula: "inv_trigo(Math.atan,",
      type: "trigo_function",
    },
    {
      name: "4",
      symbol: 4,
      formula: 4,
      type: "number",
    },
    {
      name: "5",
      symbol: 5,
      formula: 5,
      type: "number",
    },
    {
      name: "6",
      symbol: 6,
      formula: 6,
      type: "number",
    },
    {
      name: "multiplication",
      symbol: "×",
      formula: "*",
      type: "operator",
    },
    {
      name: "factorial",
      symbol: "n!",
      formula: "FACTORIAL",
      type: "math_function",
    },
    {
      name: "exp",
      symbol: "exp",
      formula: "Math.exp",
      type: "math_function",
    },
    {
      name: "ln",
      symbol: "ln",
      formula: "Math.log",
      type: "math_function",
    },
    {
      name: "log",
      symbol: "log",
      formula: "Math.log10",
      type: "math_function",
    },
    {
      name: "1",
      symbol: 1,
      formula: 1,
      type: "number",
    },
    {
      name: "2",
      symbol: 2,
      formula: 2,
      type: "number",
    },
    {
      name: "3",
      symbol: 3,
      formula: 3,
      type: "number",
    },
    {
      name: "subtraction",
      symbol: "–",
      formula: "-",
      type: "operator",
    },
    {
      name: "power",
      symbol: "x<sup>y</sup>",
      formula: POWER,
      type: "math_function",
    },
    {
      name: "power",
      symbol: "10<sup>x</sup>",
      formula: POWER,
      type: "math_function",
    },
    {
      name: "trunc",
      symbol: "trunc",
      formula: "Math.trunc(",
      type: "math_function",
    },
    {
      name: "floor",
      symbol: "floor",
      formula: "Math.floor(",
      type: "math_function",
    },
    {
      name: "ceil",
      symbol: "ceil",
      formula: "Math.ceil(",
      type: "math_function",
    },
    {
      name: "round",
      symbol: "round",
      formula: "Math.round(",
      type: "math_function",
    },
    {
      name: "sign",
      symbol: "sign",
      formula: "Math.sign(",
      type: "math_function",
    },
    {
      name: "fixedToExponent",
      symbol: "F-E",
      formula: "toExponent(",
      type: "math_function",
    },
    {
      name: "ANS",
      symbol: "ANS",
      formula: "ans",
      type: "number",
    },
    {
      name: "percent",
      symbol: "%",
      formula: "/100",
      type: "number",
    },
    {
      name: "comma",
      symbol: ".",
      formula: ".",
      type: "number",
    },
    {
      name: "0",
      symbol: 0,
      formula: 0,
      type: "number",
    },
    {
      name: "calculate",
      symbol: "=",
      formula: "=",
      type: "calculate",
    },
    {
      name: "addition",
      symbol: "+",
      formula: "+",
      type: "operator",
    },
    {
      name: "Inverse",
      symbol: "1/x",
      formula: "(1/",
      type: "number",
    },
    {
      name: "mod",
      symbol: "mod",
      formula: "%",
      type: "operator",
    },
    {
      name: "value-mod",
      symbol: "|x|",
      formula: "Math.abs(",
      type: "operator",
    },
    {
      name: "memory-store",
      symbol: "MS",
      formula: false,
      type: "memory_function",
    },
    {
      name: "memory-clear",
      symbol: "MC",
      formula: false,
      type: "memory_function",
    },
    {
      name: "memory-recall",
      symbol: "MR",
      formula: false,
      type: "memory_function",
    },
    {
      name: "memory-add",
      symbol: "M+",
      formula: false,
      type: "memory_function",
    },
    {
      name: "memory-subtract",
      symbol: "M-",
      formula: false,
      type: "memory_function",
    },
  ];